### ISSUE TITLE
npm release?

### ISSUE THREAD

**Issue by remorses** [IBM/graphql-query-generator#3]
When will you release on npm? you should also change the name given that `graphql-query-generator` is already taken

**Comment by Alan-Cha** [comment]
@remorses Cool to see that there is interest in our project! We will release it tomorrow. And thank you for the advice!

**Comment by Alan-Cha** [comment]
Sorry, I should have closed this issue a while back. You can find our package on npm package [here](https://www.npmjs.com/package/ibm-graphql-query-generator) but I can see you have already been using it! 🥂
